sudo: false
language: node_js
node_js:
- '9'
install:
- cd api && npm install
deploy:
- provider: elasticbeanstalk
  access_key_id: AKIAIGOTGINQCLC64I6Q
  secret_access_key:
    secure: YVcDd/ffH2g6EWAu92Y20bDxwKn3izRgZX1Kfl+WJOZ+F1OvsaDU+n+Me3WLBks3S8dfDOBeYJhSz3xvic6ds6BqkayhuM8oOdGgx+eINuNrZMa+9KyB1IoRsG0y+Xmy2gMbzKLyhdplJ4HPhfBGn2QYKHZmNcUeWE9Qm5S0MiDAjvIyFBDsoRELsS3Vq9Azg1BFazQJzKN1Iv36mBZg3Lry8h8lhMcColGp5/ARyyAZ39n+HteSo0VAYbPvZc8QSPuA1DllQntVn6HtLsZirNggns174zUWBQs6mX0wGcLwFnGO9tTTAsoHI61JMydUBj32oloMk+daPvRXZYthJAM/WQydTMYy+Q9D8nq+VLrRwmDbXkUbrxsvYl6H/cSIJb7rnx9G0+P9YKedZqIfkER6cZR9dNZyWcvQQquWgN6oCQfzdsNdBnB0oK5JQMccVaF6ms3seLJO4a1tKzM3wlqFNWgmOkLAjzFw5wpWer7PswA6Sa3O8tydhd5WmIafsJen9x/p7sNzhy9Q9UMZybWR5x1MZt4cEI7KwG+aOglerVfGtZW3PJLi7tdxmWqpPpVSrXfS9QnQ9JSUqFvD5Q+qr+32veDG4SAmtlRx/QUfFDLnwz/HaQlDf/h4ze4gne2JjiJ74TKXmeGt1mcJbBUnQKoeU0WVUIW0meKw0gM=
  region: us-east-2
  app: api
  env: api-dev
  bucket_name: elasticbeanstalk-us-east-2-905020680040
  skip_cleanup: true
  on:
    branch: master
    repo: hackpsu-tech/hackPSUS2018-api
notifications:
  slack:
    secure: mo6+1fef5hlltkY3Wcck89RPlkSoKs2EtENjudcU64PSCNp+kWodQElJnN8aY+Qcmn3s+NR9CVd0RTrRAapDVbKWkakBHw5SaUG9ly14/SiNSA04tnzxIMFdtJHpvHs8+dgNOY9iDeFAyCg6/FqGYyl1D7INwIkNfyaG6ymgQQb9udd2cz7JK8ztMtbmDi42kg83VUgA16Hah+160uh4u0rk4F1U2vXEMFRnIJ5DG+7yHtf8UIrvsQ40JhARKwhajrmRP++xw0fSiTvauXNte2oNGULPi7UBiMvcCnGeDycYdMYAQru42CHtlM91m6LCnF8pb42HHFjij37T3NhNUz18elnioikKs7m/PWbgs2sNcW7HsxV1x7dqlW0DRYKe/5eSQIN/Q4dw8T3QnRi+D6EPfmZYSQNh8podd93kIF3A8TjtlbcOhp1M7PTMZOfARfG3c3tKsLahYcOr3D1QudOBh8gVni00jKlKFyVuuELkDwykvZR0qm9HiVpFXDAPk+FaOQwgMKR/VoP1ycgU+a9jyNnZE7c4tJ/bnZK+ESF9PTp1MeOKgfkwm1cEcxxNAHeRmoUfxeEi9b7HvKQHNNb+sInlCXaN9lAU3YgMUKSYgptHtqG7YgnTf6arUrlihADC0g+s20pYOxxwbxUQJTOv6Q0z55eob5A46flJ+Cg=
env:
  matrix:
    secure: N+I5e7mADmHGFJ8BJZOAFwsUPcVa6DP4qtHb74hIZS+Mk8AZggmwha8Rr6BT+DTAi8ZKTFqm2T1LSNKJRAD8nedLLmr+Mw9zxfGq/08Pbys5ZkpFlQCWDcpbiuvtNg3cF+FvCTMqLyt4aOAUBudNQh2WsAtKWZwHtyqThA7AwCfcdLpYMLM6NYhp50Ngg3zSRIuWJHcDe+5WQP5hS+J6IbcuhgSQZmpJLRmE60mhtQYW4QUwKkU4pe7nMLTebU05/EnKIvKp/IU3LUJCljmppoZ7sA83LgswX3FirK56R5Ry1mtfUbRpgUjLX3nL6ePRSdyC0g5v14s8nx0RenebSUyRACQ6f6bH34Q0KO3fefQRxdSWNymXeJYQKtzZTB71MYIghWjD4MPicql+kHCfWhwAIbeAZoZwSOSGJv+D/MfkmQzDa19SXGT9VM85dFQ1OBFH/+EJJv9vFWA5aD4nIFRav61HNk63x1mI5YbTzvv4x0Pqc5Ot2fsJHslaYz2cqITm8ti7axmSul1Rn0FkAO5Tz0KjgSOJ2ggMCW5yCXIsZGdhJui2+mW5vPYOrQ0/LIFkCzWnr+ScY/KH2FzEbwGkaMGo5H20uQLkk+6vfI4Qgoj8ip875P5qNrCKdglYr1nqm22HWHyKoVtgx8iOEum+BScz87TVaoTkNq++B44=                                                
  global:
    secure: ZmFNm36yRF1EC3DOe4zGn1Uh2nHw9WBgSm/lxn9oLQXM9bUCn/eBcUhq2PCICmlRvA1EbJSkxVYDdIeUb6zA7XpN89G6FIoKSBmkhuMPVNR7ao6QmJ/71RHiVgU17dDroyQT2vPfPL4PxxRw0AEbeXevRjrGzHHOifT0DajT+PTlQmk6nJn8pNGUwt1mwBcGoU2MDr86yISAI7J5S9lCzPcH2uZvEV/fFvJRhteVqtqSS/9GNTOZ+F8uL6O7lGiOjDceqH12qbG9i0+2pHj/G6kCtdB3XBwZEoUzBdv0vhcHqRQE2jcKGkJ7BTfvRQOtp/pdfepuKmFYzy8tXuoKRM8IGGDruytlqCtAo/0C/N+W9iHHh1lFD643SDPEfY4hN9IhcXmEf4dNQVWpPZO+9L00vViOl08sar+Q+Elaotw6dOLXy6tOiMJYFm33johdaF/P+hluZSQKM1X2aqAsAZOSbAQaA4B9ZvhLFETJxvcuDTWcL0MTAFoW44OfC92rd/EAsx+FR2M4qzyY8PRYiWBV54K+pgGxwrcsOjuXl5f/yRQnFA5BNwdyym4zp6nC0+RUz6KB4xLFHU3SpObHvvAC1vZ8oZ9QS3H9912frB/bzfkJDhSHom09+DkGP3mHklFcL3nk7+WIYpENrjZeVw4PYiHpOfR+kAM6zcOC0BE=
