sudo: false
language: node_js
#cache: yarn
branches:
  only:
  - master
  - dev
node_js:
- '10'
before_install:
- npm i -g node-cipher
- npm i -g grunt-cli
install:
- npm install
- grunt travis --test
script:
- npm test
notifications:
  slack:
    secure: UextL6uGIBN6Py0Hhze3YkNwioTVX5bR0wkiLQwKBWgS4/1zmDd+hXjXFl3QBtJJ67U+gGXsqcinVpCPct/n9ukzyX+RLsjI+NKL+C01/GouWNQR0+hH7qNlREgymF9VbmhPYRs5grcp6e2bTbv0wcdnndFcFiTPTLfOA4whrou9f/0KY2yMG6R+xyoWb4T08RtS1sfGCyiQPil8T9Xl4r8EnWxSNLCTRbI44XEPKCQ87/V9qKmPU2Z7jHkKdm9gMj7E7K7dmzLKnOlyy2/zFgIj61bBLp6mmpL9xzg0jGfKFv87040j9qCH+Jnk7VCwR3N7S6+zzcqVboLpTNvSPuXHRW0P2MhLgRJZsLyymMw6gB5apooHK/jQUJseJ49zxhxwzuoFNiNYOHwWINHNZUuRJr8qT4LHLaIhh2djT+0ILi99j8OBuFDD/stPEqkvDQMyEbaXN6IUDyQpbwpbg7/lNeOuaetgyBWByJYfj9J609xpAiCTTp2QByIYTuwfREglUHcKEcOnhr5JjHltLVYHPkzxgc8gP6SkzrvTMQAHGYQZ+QGzNTFpoFbvccS+jp14sJktczti1J6hQCX7huUUFvGp+6RBqrHEJTjC0RJ7E4DQduJERhgFoNr7T2yh6FHI6tn0W0fRqYFn5mg4fMTwknN6emeWNqOdgNJyz8I=
env:
  global:
  - SQL_DATABASE=test
  - APP_ENV=test
  - secure: BnuMnfm1PcOe+SXlwSIGC0zNKE+BT8A47DVmAvgLkizOA9I36LGYEfh5Vnk3fTArfhU6npKYuA5al1S8zEy8eGm2b5wNAOeWzpbOf4LEp8/q5khvhg0VOuFMH1LxNo01X2FbMOURuYIBLA886WUY5tDQqs/YGNrQQrbgWU8OW4WoWGr+G/SrKvi4/vpBLiwG9/jKvaayy1F5oWhEV/bFvgM/73KcQe32jkpp9M0vI7jqbiaO08wI1q8Z6AsrlcCd9fgS/7FZ3n68fTNmtjBEI9xP/qmjHQYtbI6U4Gw3kbzJ9PCBzjxiSRaZrJRBv6ypJ1cJsf51KBVIdi3nkHOKJNJeKSm0AgTJvO0W3iIQpH6glTcOjFMSyEZ0m9DXv74Pe6Q0+NE+eEkvunA/Gr7cTJoRtpN2XanK1jT5rS+88Dw0gMWNDRdnv1LQmwERJ9ENhruQe3MSslF2I/hNRdm+7Uu0UNlSMD5wrlkCctyVR6pAR2ixuE+1rGQQwpwDNhxGoduQmktpfaC0DYXLvYkQaGS6TbOQf4Ju3zyYnvzB8PQC7zUOpXP/Vyf561koQzmGUNrIhiADmdPfEo5mGuRqxTdJUyqu9Cwt5LMYjG0SpdW//aHqyRvGyoapRK1mKsZCM6ek2340WhwyZy7WDy/5XhoeI+gd5JvbGsAkfW2ECy0=
  - secure: mBSRMBK3w1pJ6Ap/Ty4QiH8n6zhcYsk8SSevQWWP83Uiy8nnMcyjAL8nINAH80NMYaPUZ7Tc5pzxhTpRDw1nGXhgUsoc3cS9T01aHPzKFAArx6fFzOSxZFmoFhYa5jl4nvjRF0rP7vaPFlcAz9qFa8kAchgRgOgYzcrgJWKZyv0jiNCJYJzFyukgn7i3oLXyQQMZ1WXbw6wuZXIFuO4zH8uiUc9BU0oZSAmnGiuWVtpckn1N9TTxpiKyMD1gNryC6RwT7zlLwXdupRhG01yXlu3yMM0ufXLRj7N5XkVvAh+xDoop0/q7uzIkHOaVV1fvRVAeVpDvRvcMighIUmiwBTuJJ4Vi6UF/tTunxU2GlZHjuUj/w2r2mNfqsVzj/l2+69LJwAWNt6uI5c1Yr3FaAAcpeXWziN8yz6mtw3KBLnBd+JAH400Wm3fnxcePuxPQauid4V9X9iRz91HY+eqE6jM7da5ak9+9syO69x+aqBPYtMTIy4R81qfb2XurR16hl18NnN12NKMrNJ6illAVcbjR6VCyI7JayJMRgG2xHKc9juiglTG7XLgLnJ4m4X6GRhN161yPyZXF/7cGszcFY3BhvOHydObKX5CvP5CK5fGh2NgusW7+GobegBO6cTSVaKACL1qkHIWyWroWZ8+F1lb8d1lc2YT0JHcPzyP3nng=
before_deploy:
- npm i -g node-cipher
- cd $TRAVIS_BUILD_DIR
- npm install && grunt prep --production
- nodecipher decrypt ./encrypted/hackpsu18-ecc9dc4878c6.json.enc "./hackpsu18-ecc9dc4878c6.json" -p ${PKEY_PASS} -a aes-256-cbc-hmac-sha256
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: hackpsu18-ecc9dc4878c6.json
  project: hackpsu18
  config: app.v2.yaml
  on: master
