sudo: false
language: node_js
branches:
  only:
  - master
node_js:
- '8'
install:
- cd api && npm install
notifications:
  slack:
    secure: UextL6uGIBN6Py0Hhze3YkNwioTVX5bR0wkiLQwKBWgS4/1zmDd+hXjXFl3QBtJJ67U+gGXsqcinVpCPct/n9ukzyX+RLsjI+NKL+C01/GouWNQR0+hH7qNlREgymF9VbmhPYRs5grcp6e2bTbv0wcdnndFcFiTPTLfOA4whrou9f/0KY2yMG6R+xyoWb4T08RtS1sfGCyiQPil8T9Xl4r8EnWxSNLCTRbI44XEPKCQ87/V9qKmPU2Z7jHkKdm9gMj7E7K7dmzLKnOlyy2/zFgIj61bBLp6mmpL9xzg0jGfKFv87040j9qCH+Jnk7VCwR3N7S6+zzcqVboLpTNvSPuXHRW0P2MhLgRJZsLyymMw6gB5apooHK/jQUJseJ49zxhxwzuoFNiNYOHwWINHNZUuRJr8qT4LHLaIhh2djT+0ILi99j8OBuFDD/stPEqkvDQMyEbaXN6IUDyQpbwpbg7/lNeOuaetgyBWByJYfj9J609xpAiCTTp2QByIYTuwfREglUHcKEcOnhr5JjHltLVYHPkzxgc8gP6SkzrvTMQAHGYQZ+QGzNTFpoFbvccS+jp14sJktczti1J6hQCX7huUUFvGp+6RBqrHEJTjC0RJ7E4DQduJERhgFoNr7T2yh6FHI6tn0W0fRqYFn5mg4fMTwknN6emeWNqOdgNJyz8I=
env:
  global:
    secure: BnuMnfm1PcOe+SXlwSIGC0zNKE+BT8A47DVmAvgLkizOA9I36LGYEfh5Vnk3fTArfhU6npKYuA5al1S8zEy8eGm2b5wNAOeWzpbOf4LEp8/q5khvhg0VOuFMH1LxNo01X2FbMOURuYIBLA886WUY5tDQqs/YGNrQQrbgWU8OW4WoWGr+G/SrKvi4/vpBLiwG9/jKvaayy1F5oWhEV/bFvgM/73KcQe32jkpp9M0vI7jqbiaO08wI1q8Z6AsrlcCd9fgS/7FZ3n68fTNmtjBEI9xP/qmjHQYtbI6U4Gw3kbzJ9PCBzjxiSRaZrJRBv6ypJ1cJsf51KBVIdi3nkHOKJNJeKSm0AgTJvO0W3iIQpH6glTcOjFMSyEZ0m9DXv74Pe6Q0+NE+eEkvunA/Gr7cTJoRtpN2XanK1jT5rS+88Dw0gMWNDRdnv1LQmwERJ9ENhruQe3MSslF2I/hNRdm+7Uu0UNlSMD5wrlkCctyVR6pAR2ixuE+1rGQQwpwDNhxGoduQmktpfaC0DYXLvYkQaGS6TbOQf4Ju3zyYnvzB8PQC7zUOpXP/Vyf561koQzmGUNrIhiADmdPfEo5mGuRqxTdJUyqu9Cwt5LMYjG0SpdW//aHqyRvGyoapRK1mKsZCM6ek2340WhwyZy7WDy/5XhoeI+gd5JvbGsAkfW2ECy0=
before_deploy:
- npm i -g node-cipher
- prepare_deploy.sh
- openssl aes-256-cbc -K $encrypted_2002c5038e25_key -iv $encrypted_2002c5038e25_iv
- in hackpsu18-ecc9dc4878c6.json.enc -out hackpsu18-ecc9dc4878c6.json
- d
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: hackpsu18-ecc9dc4878c6.json
  project: hackpsu18
  config: api/app.yaml
  on: master
